[32m2025-01-20 23:08:19 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 74d92192-5f9d-423e-9687-c1901adbe223 - 72514 - LOGS_CAPTURED - Started capturing logs in process (pid: 72514).
[32m2025-01-20 23:08:19 +0800[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 74d92192-5f9d-423e-9687-c1901adbe223 - 72514 - hackernews_stories - STEP_START - Started execution of step "hackernews_stories".
[32m2025-01-20 23:08:20 +0800[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 74d92192-5f9d-423e-9687-c1901adbe223 - 72514 - hackernews_stories - STEP_FAILURE - Execution of step "hackernews_stories" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "hackernews_stories"::

TypeError: unsupported operand type(s) for -: 'Response' and 'int'

Stack Trace:
  File "/Users/jamesballesteros/miniforge3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 55, in op_execution_error_boundary
    yield
  File "/Users/jamesballesteros/miniforge3/envs/dagster/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/jamesballesteros/miniforge3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jamesballesteros/miniforge3/envs/dagster/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jamesballesteros/MLOPS/dasci270-dagster/hackernews/hackernews/assets.py", line 12, in hackernews_stories
    scope = range(latest_item - 500, latest_item - 1000)
                  ~~~~~~~~~~~~^~~~~
[0m
